### ISSUE TITLE
Migrate to JCEF instead of JavaFX browser control

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/AvaloniaRider#74]
Since JavaFX is being obsoleted as an IntelliJ component, and JCEF, on the other hand, being included into it by default, we'll have to migrate from JavaFX to JCEF for the plugin version targeting Rider 2020.2+.

**TODO:**
- [x] remove the JavaFX plugin requirement from the README
- [x] remove the JavaFX plugin requirement from the `plugin.xml`
- [x] remove the JavaFX plugin requirement from the `build.gradle`
- [x] remove/fix all the associated TODOs in code

**Comment by wdcossey** [comment]
I can't get the HtmlPreview to work (always a 404 from `Avalonia.Designer.HostApp`) but would think it would be something like the following.

```
package me.fornever.avaloniarider.idea.editor

import com.intellij.ui.jcef.JBCefBrowser
import com.jetbrains.rd.util.lifetime.Lifetime
import me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController
import java.awt.BorderLayout
import javax.swing.JPanel

class HtmlPreviewEditorComponent(lifetime: Lifetime, controller: AvaloniaPreviewerSessionController): JPanel() {

    private lateinit var webView: JBCefBrowser

    init {
        layout = BorderLayout()

        webView = JBCefBrowser()

        add(webView.component, BorderLayout.CENTER)

        controller.htmlTransportStarted.advise(lifetime) {
            connectTo(it.uri)
        }
    }

    private fun connectTo(uri: String) {
        webView.loadURL(uri)
    }
}
```
